apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../apps/platform/apps

patchesStrategicMerge:
  - nginx-ingress-dev.yaml
  - cert-manager-dev.yaml
  - external-dns-dev.yaml
  - keda-dev.yaml

namespace: argocd

namePrefix: dev-

commonLabels:
  environment: dev
  cluster: development