---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@example.com  # Update with actual email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        rfc2136:
          nameserver: "dns-server.example.com:53"  # Update with actual DNS server
          tsigKeyName: "external-dns"
          tsigSecretSecretRef:
            name: external-dns-tsig-secret
            key: tsig-secret

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com  # Update with actual email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        rfc2136:
          nameserver: "dns-server.example.com:53"  # Update with actual DNS server
          tsigKeyName: "external-dns"
          tsigSecretSecretRef:
            name: external-dns-tsig-secret
            key: tsig-secret