---
# Alertmanager Configuration
config:
  global:
    smtp_smarthost: 'SMTP_HOST_PLACEHOLDER:587'
    smtp_from: 'alerts@example.com'
    smtp_auth_username: 'SMTP_USERNAME_PLACEHOLDER'
    smtp_auth_password: 'SMTP_PASSWORD_PLACEHOLDER'
  
  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    receiver: 'web.hook'
    routes:
    - match:
        environment: dev
      receiver: 'dev-team'
      routes:
      - match:
          severity: critical
        receiver: 'dev-critical'
    - match:
        environment: prod
      receiver: 'prod-team'
      routes:
      - match:
          severity: critical
        receiver: 'prod-critical'
  
  receivers:
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://example.com/webhook'
  
  - name: 'dev-team'
    email_configs:
    - to: 'dev-team@example.com'
      subject: '[DEV] {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}
  
  - name: 'dev-critical'
    email_configs:
    - to: 'dev-oncall@example.com'
      subject: '[DEV CRITICAL] {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}
    slack_configs:
    - api_url: 'SLACK_WEBHOOK_URL_PLACEHOLDER'
      channel: '#dev-alerts'
      title: '[DEV CRITICAL] {{ .GroupLabels.alertname }}'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
  
  - name: 'prod-team'
    email_configs:
    - to: 'prod-team@example.com'
      subject: '[PROD] {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}
  
  - name: 'prod-critical'
    email_configs:
    - to: 'prod-oncall@example.com'
      subject: '[PROD CRITICAL] {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}
    slack_configs:
    - api_url: 'SLACK_WEBHOOK_URL_PLACEHOLDER'
      channel: '#prod-alerts'
      title: '[PROD CRITICAL] {{ .GroupLabels.alertname }}'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    pagerduty_configs:
    - routing_key: 'PAGERDUTY_ROUTING_KEY_PLACEHOLDER'
      description: '[PROD CRITICAL] {{ .GroupLabels.alertname }}'

# Persistence
persistence:
  enabled: true
  storageClass: "standard"
  size: 10Gi

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Service
service:
  type: ClusterIP
  port: 9093

# Monitoring
serviceMonitor:
  enabled: true

# Security
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534