---
# Grafana Configuration
admin:
  # Disable default admin user - use OIDC instead
  enabled: false

# OIDC Configuration placeholders
env:
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_GENERIC_OAUTH_NAME: "OIDC"
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "OIDC_CLIENT_ID_PLACEHOLDER"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "OIDC_CLIENT_SECRET_PLACEHOLDER"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "OIDC_AUTH_URL_PLACEHOLDER"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "OIDC_TOKEN_URL_PLACEHOLDER"
  GF_AUTH_GENERIC_OAUTH_API_URL: "OIDC_USERINFO_URL_PLACEHOLDER"
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
  GF_AUTH_DISABLE_LOGIN_FORM: "true"

# Persistence
persistence:
  enabled: true
  storageClassName: "standard"
  size: 10Gi

# Dashboard provisioning
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# Datasource provisioning
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://victoria-metrics-k8s-stack-vmsingle.observability:8428
      access: proxy
      isDefault: true
      editable: true

# Service configuration
service:
  type: ClusterIP
  port: 80

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Monitoring
serviceMonitor:
  enabled: true

# Security
securityContext:
  runAsNonRoot: true
  runAsUser: 472
  fsGroup: 472

# Extra volumes for dashboard provisioning
extraVolumes:
  - name: dashboards-default
    configMap:
      name: grafana-dashboards

extraVolumeMounts:
  - name: dashboards-default
    mountPath: /var/lib/grafana/dashboards/default
    readOnly: true
