---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
    platform: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    platform: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    name: external-dns
    platform: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    name: keda
    platform: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    environment: dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: prod

---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    platform: "true"