---
# Example VMRule for application monitoring
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: example-app-alerts
  namespace: default
spec:
  groups:
  - name: example-app
    rules:
    # High CPU usage alert
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{container="app"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
        service: example-app
      annotations:
        summary: "High CPU usage detected"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} has been using more than 80% CPU for 5 minutes"
    
    # High memory usage alert
    - alert: HighMemoryUsage  
      expr: container_memory_usage_bytes{container="app"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
        service: example-app
      annotations:
        summary: "High memory usage detected"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using more than 90% of its memory limit"
    
    # Application error rate alert
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
      for: 2m
      labels:
        severity: critical
        service: example-app
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }} for service {{ $labels.service }}"
    
    # Pod restart alert
    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total[1h]) > 3
      for: 0m
      labels:
        severity: warning
        service: example-app
      annotations:
        summary: "Pod is restarting frequently"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted {{ $value }} times in the last hour"