apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  project: platform
  
  source:
    repoURL: https://github.com/Proleptic-Admin/cluster-config
    targetRevision: HEAD
    path: manifests/rbac
    
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m