---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-admin
  namespace: kube-system
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-admin
subjects:
- kind: ServiceAccount
  name: platform-admin
  namespace: kube-system
- kind: Group
  name: platform-admins
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-operator
  namespace: kube-system
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-operator
subjects:
- kind: ServiceAccount
  name: platform-operator
  namespace: kube-system
- kind: Group
  name: platform-operators
  apiGroup: rbac.authorization.k8s.io